[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]

[rpc_endpoints]
kairos = "${KAIROS_RPC_URL}"

[etherscan]
kairos = { key = "${KAIA_SCAN_API_KEY}" }

[dependencies]
solady = "0.1.19"
forge-std = "1.9.7"

[soldeer]
# whether soldeer manages remappings
remappings_generate = false
# whether soldeer re-generates all remappings when installing, updating or uninstalling deps
remappings_regenerate = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options